package dev.gokanaz.kplayer.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006B5F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF72F8E4)
val md_theme_light_onPrimaryContainer = Color(0xFF00201C)
val md_theme_light_secondary = Color(0xFF4A635E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E1)
val md_theme_light_onSecondaryContainer = Color(0xFF06201C)
val md_theme_light_tertiary = Color(0xFF456179)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC9E5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E30)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFB)
val md_theme_light_onBackground = Color(0xFF191C1B)
val md_theme_light_surface = Color(0xFFFAFDFB)
val md_theme_light_onSurface = Color(0xFF191C1B)
val md_theme_light_surfaceVariant = Color(0xFFDBE5E1)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4946)
val md_theme_light_outline = Color(0xFF6F7A76)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F0)
val md_theme_light_inverseSurface = Color(0xFF2E3130)
val md_theme_light_inversePrimary = Color(0xFF54DBC8)
val md_theme_light_surfaceTint = Color(0xFF006B5F)
val md_theme_light_outlineVariant = Color(0xFFBFC9C5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF54DBC8)
val md_theme_dark_onPrimary = Color(0xFF003731)
val md_theme_dark_primaryContainer = Color(0xFF005047)
val md_theme_dark_onPrimaryContainer = Color(0xFF72F8E4)
val md_theme_dark_secondary = Color(0xFFB0CCC5)
val md_theme_dark_onSecondary = Color(0xFF1C3531)
val md_theme_dark_secondaryContainer = Color(0xFF334B47)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E1)
val md_theme_dark_tertiary = Color(0xFFACC9E5)
val md_theme_dark_onTertiary = Color(0xFF123347)
val md_theme_dark_tertiaryContainer = Color(0xFF2C4960)
val md_theme_dark_onTertiaryContainer = Color(0xFFC9E5FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1B)
val md_theme_dark_onBackground = Color(0xFFE1E3E2)
val md_theme_dark_surface = Color(0xFF191C1B)
val md_theme_dark_onSurface = Color(0xFFE1E3E2)
val md_theme_dark_surfaceVariant = Color(0xFF3F4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C5)
val md_theme_dark_outline = Color(0xFF89938F)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1B)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E2)
val md_theme_dark_inversePrimary = Color(0xFF006B5F)
val md_theme_dark_surfaceTint = Color(0xFF54DBC8)
val md_theme_dark_outlineVariant = Color(0xFF3F4946)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF006B5F)

val extended_colors_pressed = Color(0x1A000000)
val extended_colors_focused = Color(0x1A000000)
val extended_colors_disabled = Color(0x61000000)
val extended_colors_hovered = Color(0x0D000000)

val surface_elevation_1 = Color(0x0DF2F7F5)
val surface_elevation_2 = Color(0x1AF2F7F5)
val surface_elevation_3 = Color(0x26F2F7F5)
val surface_elevation_4 = Color(0x33F2F7F5)
val surface_elevation_5 = Color(0x3DF2F7F5)
